services:
  - type: web
    name: pomobee-backend
    runtime: docker
    rootDir: backend
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: PORT
        value: 8080
