spring.application.name=pomodoro
server.port=8080

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/pomodoro_db
spring.datasource.username=vijayhiremath
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
