spring.application.name=pomodoro
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d5qrd0coud1c73ec0kng-a.oregon-postgres.render.com/pomobee_db
spring.datasource.username=pomobee_db_user
spring.datasource.password=9iy5oGWNQS2xrt5G7fglml2N8q2N8Xcw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
